### ISSUE TITLE
Proposal: Make Result.Error generic (or object)

### ISSUE THREAD

**Issue by draptik** [vkhorikov/CSharpFunctionalExtensions#35] opened 2017-07-09 22:22 UTC
Currently Result.Error is of type string.
IMHO it would make the Result object more expressive if Error where generic (or object).

Use case: Collecting error messages.

see http://enterprisecraftsmanship.com/2016/06/24/c-functional-extensions-nuget-library/#comment-3308367961

**Comment by smblee** [comment] 2018-03-19 20:52
Any progress on this?

**Comment by smblee** [comment] 2018-03-19 20:53
If you will approve it I will write it

**Comment by vkhorikov** [comment] 2018-03-19 20:57
That feature was actually released in 1.9.0 (`public struct Result<TValue, TError>`). Let me know if you would like to enhance it. Closing this issue.

**Closed by vkhorikov** 2018-03-19 20:57 UTC

**Comment by smblee** [comment] 2018-03-20 19:24
Is there an example where this can be used along with Result<TValue>, or even Result (where you just want to return Result.Ok without a return TValue)?

I have implmented something where `Result<TValue>` or `Result` will get returned from my Business layer and repository with string errors, then switching on the errors to a HttpStatusCode from the Controller layer.

The problem is, some Business and Repository methods actually would be more useful if they can return an object with more information on it, so we can have very comprehensive errors in the Http Response. 

This is where I hoped Result<TValue, TError> would come handy, but it seems like this means I have to have all my Business and Repositories to have a return type of Result<TValue, TError>, even when they most of the time don't need to be. (For example, if it used to be `Result` then there would be no `TValue`, but there is no way to enforce `void` TValue.)

I realize that there are no examples of using Result<TValue, TError> in your library and it would be very useful if you could provide some.

**Comment by vkhorikov** [comment] 2018-03-23 03:09
Yeah, that's inconvenient. In functional languages, this kind of issue is resolved by having an explicit type for `void` (such as `unit` in F#), but we don't have anything like that in C#.

I'll try to come up with something here.
