### ISSUE TITLE
Sign Nuget Package Assembly with strong name

### ISSUE THREAD

**Issue by rightdirection1** [vkhorikov/CSharpFunctionalExtensions#48] opened 2018-01-27 19:15 UTC
When using the the package in an asse,bly which is signed with strong name, I am not able to do so.
Could you please sign it?

**Comment by vkhorikov** [comment] 2018-01-29 13:35
I'm afraid I wouldn't be able to do that. Try this solution: https://github.com/dsplaisted/strongnamer

**Comment by pagratios** [comment] 2019-03-10 19:37
Or this one https://brutaldev.com/post/net-assembly-strong-name-signer

**Comment by petrechitashvili** [comment] 2020-01-17 06:40
> I'm afraid I wouldn't be able to do that. Try this solution: https://github.com/dsplaisted/strongnamer

@vkhorikov can you please elaborate on why you wouldn't be able to do that?

**Comment by petrechitashvili** [comment] 2020-01-17 08:54
@vkhorikov if you don't want to sign the **CSharpFunctionalExtensions** nuget package, why not create a separate one - **CSharpFunctionalExtensions.Signed** that will be signed?

I saw another issue like this one, likely a duplicate - https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/27

**Comment by vkhorikov** [comment] 2020-01-20 19:53
> can you please elaborate on why you wouldn't be able to do that?
Additional maintenance burden, difficulty of redirects. Not worth it overall given that almost no one strong names libraries anymore.

Two libraries wouldn't solve the issue with maintenance, and can potentially add more problems with versioning.

**Comment by shuelsmeier** [comment] 2020-09-29 06:13
We are using BizTalk that forces us to use signed assemblies and I would like to use your NuGet package. Can u reconsider signing it?

**Comment by vkhorikov** [comment] 2020-10-06 11:42
@shuelsmeier what about the workaround with the https://github.com/dsplaisted/strongnamer library?

**Comment by juflo** [comment] 2020-12-07 14:09
Hi @vkhorikov 
Strong signing ourselves nuget dependencies is a maintenance nightmare for end users (updating package version, not even talking about dealing with [InternallyVisible] attributes).
Did you have a look to Microsoft guidance for open-source libraries regarding strong signing ?
[https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming](url)

**Comment by vkhorikov** [comment] 2021-02-16 15:57
A signed version of the library is in the plans. Closing this issue as a duplicate of https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/27

**Closed by vkhorikov** 2021-02-16 15:57 UTC
